//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapter
    {
        public int ID { get; set; }
        public int StoryID { get; set; }
        public int ChapterNum { get; set; }
        public string ChapterName { get; set; }
        public string Slug { get; set; }
        public string Text { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Story Story { get; set; }
    }
}
